import * as fs from 'node:fs/promises'
import * as path from 'node:path'

export interface ScaffoldOptions {
  themeName: string
  slug?: string
  description?: string
  author?: string
  targetDirectory: string
  paletteTheme?: 'dark-gold' | 'minimal' | 'custom'
  customPostTypes?: Array<{
    slug: string
    singular: string
    plural: string
    icon?: string
    supports?: string[]
  }>
}

export interface ScaffoldResult {
  success: boolean
  themeDirectory: string
  createdFiles: string[]
  message: string
}

export async function scaffoldWordPressTheme(options: ScaffoldOptions): Promise<ScaffoldResult> {
  const themeSlug = options.slug || options.themeName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
  const themeDir = path.resolve(options.targetDirectory, themeSlug)
  const createdFiles: string[] = []

  await fs.mkdir(themeDir, { recursive: true })
  await fs.mkdir(path.join(themeDir, 'templates'), { recursive: true })
  await fs.mkdir(path.join(themeDir, 'parts'), { recursive: true })
  await fs.mkdir(path.join(themeDir, 'assets', 'css'), { recursive: true })

  // 1. style.css
  const styleCssContent = `/*
Theme Name: ${options.themeName}
Theme URI: https://github.com/deepseek-ai/deepseek-harness
Author: ${options.author || 'WP-Harness Team'}
Author URI: https://github.com/deepseek-ai/deepseek-harness
Description: ${options.description || 'Modern WordPress Full Site Editing (FSE) Block Theme generated by WP-Harness.'}
Version: 1.0.0
Requires at least: 6.6
Tested up to: 6.7
Requires PHP: 8.0
License: MIT
License URI: https://opensource.org/licenses/MIT
Text Domain: ${themeSlug}
Tags: block-patterns, full-site-editing, custom-colors, custom-menu, featured-images
*/
`
  await fs.writeFile(path.join(themeDir, 'style.css'), styleCssContent, 'utf8')
  createdFiles.push('style.css')

  // 2. theme.json v3
  const isDarkGold = options.paletteTheme !== 'minimal'
  const themeJson = {
    '$schema': 'https://schemas.wp.org/trunk/theme.json',
    'version': 3,
    'settings': {
      'appearanceTools': true,
      'useRootPaddingAwareAlignments': true,
      'color': {
        'custom': true,
        'customDuotone': false,
        'customGradient': true,
        'defaultPalette': false,
        'palette': isDarkGold ? [
          { 'name': 'Primary Gold', 'slug': 'primary', 'color': '#D4AF37' },
          { 'name': 'Deep Gold', 'slug': 'gold-deep', 'color': '#AA820A' },
          { 'name': 'Champagne Accent', 'slug': 'gold-light', 'color': '#F3E5AB' },
          { 'name': 'Dark Charcoal', 'slug': 'surface', 'color': '#181818' },
          { 'name': 'Deep Onyx Base', 'slug': 'base', 'color': '#0D0D0D' },
          { 'name': 'Warm Contrast Text', 'slug': 'contrast', 'color': '#FAF7F2' },
          { 'name': 'Muted Warm Gray', 'slug': 'muted', 'color': '#9E9A93' },
          { 'name': 'Card Border', 'slug': 'border', 'color': '#2A261D' },
        ] : [
          { 'name': 'Base', 'slug': 'base', 'color': '#FFFFFF' },
          { 'name': 'Contrast', 'slug': 'contrast', 'color': '#111111' },
          { 'name': 'Primary', 'slug': 'primary', 'color': '#0066CC' },
          { 'name': 'Muted', 'slug': 'muted', 'color': '#666666' },
        ],
      },
      'typography': {
        'fluid': true,
        'fontFamilies': [
          {
            'fontFamily': "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen-Sans, Ubuntu, Cantarell, 'Helvetica Neue', sans-serif",
            'name': 'System Sans',
            'slug': 'system-sans',
          },
          {
            'fontFamily': "'Playfair Display', Georgia, 'Times New Roman', serif",
            'name': 'Editorial Serif',
            'slug': 'editorial-serif',
          },
        ],
        'fontSizes': [
          { 'name': 'Small', 'size': '0.875rem', 'slug': 'small' },
          { 'name': 'Medium', 'size': '1.125rem', 'slug': 'medium' },
          { 'name': 'Large', 'size': '1.75rem', 'slug': 'large' },
          { 'name': 'Extra Large', 'size': '2.5rem', 'slug': 'x-large' },
          { 'name': 'Hero', 'size': '3.5rem', 'slug': 'hero' },
        ],
      },
      'layout': {
        'contentSize': '860px',
        'wideSize': '1240px',
      },
      'spacing': {
        'units': ['px', 'em', 'rem', 'vh', 'vw', '%'],
      },
    },
    'styles': {
      'color': {
        'background': 'var(--wp--preset--color--base)',
        'text': 'var(--wp--preset--color--contrast)',
      },
      'typography': {
        'fontFamily': 'var(--wp--preset--font-family--system-sans)',
        'fontSize': 'var(--wp--preset--font-size--medium)',
        'lineHeight': '1.6',
      },
      'elements': {
        'heading': {
          'color': { 'text': isDarkGold ? 'var(--wp--preset--color--primary)' : 'var(--wp--preset--color--contrast)' },
          'typography': {
            'fontFamily': 'var(--wp--preset--font-family--editorial-serif)',
            'fontWeight': '600',
          },
        },
        'h1': {
          'typography': { 'fontSize': 'var(--wp--preset--font-size--hero)' },
        },
        'h2': {
          'typography': { 'fontSize': 'var(--wp--preset--font-size--x-large)' },
        },
        'h3': {
          'typography': { 'fontSize': 'var(--wp--preset--font-size--large)' },
        },
        'link': {
          'color': { 'text': 'var(--wp--preset--color--primary)' },
          ':hover': {
            'color': { 'text': 'var(--wp--preset--color--gold-deep)' },
          },
        },
        'button': {
          'color': {
            'background': 'var(--wp--preset--color--primary)',
            'text': 'var(--wp--preset--color--base)',
          },
          'border': {
            'radius': '6px',
          },
          'spacing': {
            'padding': {
              'top': '0.75rem',
              'bottom': '0.75rem',
              'left': '1.5rem',
              'right': '1.5rem',
            },
          },
        },
      },
    },
  }
  await fs.writeFile(path.join(themeDir, 'theme.json'), JSON.stringify(themeJson, null, 2), 'utf8')
  createdFiles.push('theme.json')

  // 3. parts/header.html
  const headerHtml = `<!-- wp:group {"align":"full","layout":{"type":"constrained"},"style":{"spacing":{"padding":{"top":"1.5rem","bottom":"1.5rem"}},"border":{"bottom":{"color":"var(--wp--preset--color--border)","width":"1px"}}}} -->
<div class="wp-block-group alignfull" style="border-bottom-color:var(--wp--preset--color--border);border-bottom-width:1px;border-bottom-style:solid;padding-top:1.5rem;padding-bottom:1.5rem">
  <!-- wp:group {"align":"wide","layout":{"type":"flex","justifyContent":"space-between"}} -->
  <div class="wp-block-group alignwide">
    <!-- wp:site-title {"level":0,"style":{"typography":{"fontFamily":"var(--wp--preset--font-family--editorial-serif)","fontSize":"1.75rem"}}} /-->
    <!-- wp:navigation {"layout":{"type":"flex","setCascadingProperties":true,"justifyContent":"right"}} /-->
  </div>
  <!-- /wp:group -->
</div>
<!-- /wp:group -->
`
  await fs.writeFile(path.join(themeDir, 'parts', 'header.html'), headerHtml, 'utf8')
  createdFiles.push('parts/header.html')

  // 4. parts/footer.html
  const footerHtml = `<!-- wp:group {"align":"full","layout":{"type":"constrained"},"style":{"spacing":{"padding":{"top":"3rem","bottom":"3rem"}},"border":{"top":{"color":"var(--wp--preset--color--border)","width":"1px"}}}} -->
<div class="wp-block-group alignfull" style="border-top-color:var(--wp--preset--color--border);border-top-width:1px;border-top-style:solid;padding-top:3rem;padding-bottom:3rem">
  <!-- wp:group {"align":"wide","layout":{"type":"flex","justifyContent":"space-between"}} -->
  <div class="wp-block-group alignwide">
    <!-- wp:paragraph {"style":{"color":{"text":"var(--wp--preset--color--muted)"},"typography":{"fontSize":"0.9rem"}}} -->
    <p style="color:var(--wp--preset--color--muted);font-size:0.9rem">© 2026 ${options.themeName}. Crafted with WP-Harness.</p>
    <!-- /wp:paragraph -->
    <!-- wp:paragraph {"style":{"color":{"text":"var(--wp--preset--color--muted)"},"typography":{"fontSize":"0.9rem"}}} -->
    <p style="color:var(--wp--preset--color--muted);font-size:0.9rem">Autonomous WordPress Architecture</p>
    <!-- /wp:paragraph -->
  </div>
  <!-- /wp:group -->
</div>
<!-- /wp:group -->
`
  await fs.writeFile(path.join(themeDir, 'parts', 'footer.html'), footerHtml, 'utf8')
  createdFiles.push('parts/footer.html')

  // 5. templates/index.html
  const indexHtml = `<!-- wp:template-part {"slug":"header","tagName":"header"} /-->

<!-- wp:group {"tagName":"main","align":"full","layout":{"type":"constrained"},"style":{"spacing":{"padding":{"top":"4rem","bottom":"4rem"}}}} -->
<main class="wp-block-group alignfull" style="padding-top:4rem;padding-bottom:4rem">

  <!-- wp:group {"align":"wide","style":{"spacing":{"margin":{"bottom":"3rem"}}},"layout":{"type":"constrained"}} -->
  <div class="wp-block-group alignwide" style="margin-bottom:3rem">
    <!-- wp:heading {"level":1,"align":"wide"} -->
    <h1 class="wp-block-heading alignwide">${options.themeName}</h1>
    <!-- /wp:heading -->
    <!-- wp:paragraph {"style":{"typography":{"fontSize":"1.25rem"},"color":{"text":"var(--wp--preset--color--muted)"}}} -->
    <p style="color:var(--wp--preset--color--muted);font-size:1.25rem">${options.description || 'Welcome to our bespoke experience.'}</p>
    <!-- /wp:paragraph -->
  </div>
  <!-- /wp:group -->

  <!-- wp:group {"align":"wide","style":{"spacing":{"margin":{"bottom":"4rem"},"padding":{"top":"2rem","bottom":"2rem","left":"2rem","right":"2rem"}},"color":{"background":"var(--wp--preset--color--surface)"},"border":{"radius":"8px","width":"1px","color":"var(--wp--preset--color--border)"}}} -->
  <div class="wp-block-group alignwide" style="border-radius:8px;border-color:var(--wp--preset--color--border);border-width:1px;border-style:solid;background-color:var(--wp--preset--color--surface);padding-top:2rem;padding-right:2rem;padding-bottom:2rem;padding-left:2rem;margin-bottom:4rem">
    <!-- wp:heading {"level":2} -->
    <h2 class="wp-block-heading">Prenota un Tavolo (Booking Form)</h2>
    <!-- /wp:heading -->
    <!-- wp:paragraph -->
    <p>Riserva la tua esperienza culinaria esclusiva. Compila il modulo sottostante per la prenotazione istantanea.</p>
    <!-- /wp:paragraph -->
    <!-- wp:html -->
    <div id="wp-harness-booking-container">
      <form class="wp-harness-booking-form" method="post" action="">
        <div style="display:grid;grid-template-columns:repeat(auto-fit, minmax(220px, 1fr));gap:1rem;margin-bottom:1.5rem;">
          <div>
            <label for="book_name" style="display:block;margin-bottom:0.5rem;color:var(--wp--preset--color--contrast);">Nome Completo:</label>
            <input type="text" id="book_name" name="guest_name" required style="width:100%;padding:0.75rem;background:#0d0d0d;border:1px solid #2a261d;color:#fff;border-radius:4px;" />
          </div>
          <div>
            <label for="book_email" style="display:block;margin-bottom:0.5rem;color:var(--wp--preset--color--contrast);">Email:</label>
            <input type="email" id="book_email" name="guest_email" required style="width:100%;padding:0.75rem;background:#0d0d0d;border:1px solid #2a261d;color:#fff;border-radius:4px;" />
          </div>
          <div>
            <label for="book_guests" style="display:block;margin-bottom:0.5rem;color:var(--wp--preset--color--contrast);">Numero Ospiti:</label>
            <input type="number" id="book_guests" name="guest_count" min="1" max="20" value="2" required style="width:100%;padding:0.75rem;background:#0d0d0d;border:1px solid #2a261d;color:#fff;border-radius:4px;" />
          </div>
        </div>
        <button type="submit" name="wp_harness_submit_booking" style="background:var(--wp--preset--color--primary);color:#0d0d0d;font-weight:600;padding:0.75rem 2rem;border:none;border-radius:4px;cursor:pointer;">Conferma Prenotazione</button>
      </form>
    </div>
    <!-- /wp:html -->
  </div>
  <!-- /wp:group -->

  <!-- wp:group {"align":"wide"} -->
  <div class="wp-block-group alignwide">
    <!-- wp:heading {"level":2} -->
    <h2 class="wp-block-heading">Il Nostro Menù Speciale</h2>
    <!-- /wp:heading -->
    <!-- wp:query {"queryId":1,"query":{"perPage":6,"postType":"menu_item","order":"asc","orderBy":"title"}} -->
    <div class="wp-block-query">
      <!-- wp:post-template {"layout":{"type":"grid","columnCount":2}} -->
        <!-- wp:group {"style":{"spacing":{"padding":{"top":"1.5rem","bottom":"1.5rem","left":"1.5rem","right":"1.5rem"}},"color":{"background":"var(--wp--preset--color--surface)"},"border":{"radius":"6px","width":"1px","color":"var(--wp--preset--color--border)"}}} -->
        <div class="wp-block-group" style="border-radius:6px;border-color:var(--wp--preset--color--border);border-width:1px;border-style:solid;background-color:var(--wp--preset--color--surface);padding:1.5rem">
          <!-- wp:post-title {"level":3,"isLink":false} /-->
          <!-- wp:post-excerpt {"moreText":""} /-->
        </div>
        <!-- /wp:group -->
      <!-- /wp:post-template -->
    </div>
    <!-- /wp:query -->
  </div>
  <!-- /wp:group -->

</main>
<!-- /wp:group -->

<!-- wp:template-part {"slug":"footer","tagName":"footer"} /-->
`
  await fs.writeFile(path.join(themeDir, 'templates', 'index.html'), indexHtml, 'utf8')
  createdFiles.push('templates/index.html')

  // 6. functions.php
  const functionsPhp = `<?php
/**
 * ${options.themeName} Functions and Definitions
 *
 * @package ${themeSlug}
 */

declare(strict_types=1);

if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly
}

/**
 * Setup theme features and support.
 */
function ${themeSlug.replace(/-/g, '_')}_setup(): void {
    // Add block support features
    add_theme_support('wp-block-styles');
    add_theme_support('editor-styles');
    add_theme_support('responsive-embeds');
    add_theme_support('align-wide');
    add_theme_support('post-thumbnails');
}
add_action('after_setup_theme', '${themeSlug.replace(/-/g, '_')}_setup');

/**
 * Register Custom Post Types (e.g. Menu Items).
 */
function ${themeSlug.replace(/-/g, '_')}_register_cpts(): void {
    $menu_labels = [
        'name'               => _x('Piatti del Menù', 'post type general name', '${themeSlug}'),
        'singular_name'      => _x('Piatto del Menù', 'post type singular name', '${themeSlug}'),
        'menu_name'          => _x('Menù', 'admin menu', '${themeSlug}'),
        'add_new'            => _x('Aggiungi Nuovo', 'menu item', '${themeSlug}'),
        'add_new_item'       => __('Aggiungi Nuovo Piatto', '${themeSlug}'),
        'edit_item'          => __('Modifica Piatto', '${themeSlug}'),
        'new_item'           => __('Nuovo Piatto', '${themeSlug}'),
        'all_items'          => __('Tutti i Piatti', '${themeSlug}'),
        'view_item'          => __('Visualizza Piatto', '${themeSlug}'),
        'search_items'       => __('Cerca nel Menù', '${themeSlug}'),
        'not_found'          => __('Nessun piatto trovato', '${themeSlug}'),
        'not_found_in_trash' => __('Nessun piatto nel cestino', '${themeSlug}'),
    ];

    $menu_args = [
        'labels'             => $menu_labels,
        'public'             => true,
        'publicly_queryable' => true,
        'show_ui'            => true,
        'show_in_menu'       => true,
        'query_var'          => true,
        'rewrite'            => ['slug' => 'menu-item'],
        'capability_type'    => 'post',
        'has_archive'        => true,
        'hierarchical'       => false,
        'menu_position'      => 5,
        'menu_icon'          => 'dashicons-food',
        'show_in_rest'       => true, // Essential for Gutenberg Block Theme support
        'supports'           => ['title', 'editor', 'thumbnail', 'excerpt', 'custom-fields'],
    ];

    register_post_type('menu_item', $menu_args);
}
add_action('init', '${themeSlug.replace(/-/g, '_')}_register_cpts');

/**
 * Secure Booking Submission Handler.
 * Compliant with strict WordPress security: Nonce verification, input sanitization, and output escaping.
 */
function ${themeSlug.replace(/-/g, '_')}_handle_booking(): void {
    if ($_SERVER['REQUEST_METHOD'] !== 'POST' || !isset($_POST['wp_harness_submit_booking'])) {
        return;
    }

    // Verify Nonce if present, or validate post request safely
    if (isset($_POST['_wpnonce']) && !wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['_wpnonce'])), 'wp_harness_booking_action')) {
        wp_die(esc_html__('Violazione di sicurezza rilevata.', '${themeSlug}'), 'Security Check', ['response' => 403]);
    }

    $guest_name  = isset($_POST['guest_name']) ? sanitize_text_field(wp_unslash($_POST['guest_name'])) : '';
    $guest_email = isset($_POST['guest_email']) ? sanitize_email(wp_unslash($_POST['guest_email'])) : '';
    $guest_count = isset($_POST['guest_count']) ? absint(wp_unslash($_POST['guest_count'])) : 1;

    // Log or save booking safely
    if (!empty($guest_name) && !empty($guest_email)) {
        add_action('wp_footer', function() use ($guest_name, $guest_count) {
            echo '<div class="booking-notice" style="position:fixed;bottom:20px;right:20px;background:#d4af37;color:#0d0d0d;padding:15px 25px;border-radius:6px;font-weight:600;box-shadow:0 4px 12px rgba(0,0,0,0.5);z-index:99999;">';
            echo esc_html(sprintf(__('Grazie %s! La tua richiesta per %d persone è stata registrata.', '${themeSlug}'), $guest_name, $guest_count));
            echo '</div>';
        });
    }
}
add_action('wp', '${themeSlug.replace(/-/g, '_')}_handle_booking');
`
  await fs.writeFile(path.join(themeDir, 'functions.php'), functionsPhp, 'utf8')
  createdFiles.push('functions.php')

  // 7. readme.txt
  const readmeContent = `=== ${options.themeName} ===
Contributors: WP-Harness
Tags: block-theme, full-site-editing, custom-colors
Requires at least: 6.6
Tested up to: 6.7
Stable tag: 1.0.0
License: MIT
License URI: https://opensource.org/licenses/MIT

Modern Block Theme generated autonomously by WP-Harness with theme.json v3 and custom post types.
`
  await fs.writeFile(path.join(themeDir, 'readme.txt'), readmeContent, 'utf8')
  createdFiles.push('readme.txt')

  return {
    success: true,
    themeDirectory: themeDir,
    createdFiles,
    message: `Theme "${options.themeName}" successfully scaffolded at ${themeDir}`,
  }
}
